.github/workflows/node.js.yml
=> Archive .deb and .rpm file.

.github/workflows/node.js.yml
Run self-check as part of github CI.
=> Add self-check to github build.

src-electron/util/env.js
- increase expected electron version.
=> Modify version again.

test/rendererapi.test.js
=> Adjust test for reality.

src-electron/util/string.js
removing the '+' or ‘&’ or ‘(‘ or ‘)’ symbols. Although might be not the cleanest way of doing this. Tested on my problem with #135 and it works fine.
=> attempt to fix github issue #135

src/components/ZclCreateModifyEndpoint.vue, src/components/ZclEndpointCard.vue, src/components/ZclEndpointManager.vue
Emit event from component when endpoint has been successfully validated
=> Add endpoint dialog event

src-electron/generator/helper-session.js, src-electron/util/iterator-util.js
In particular, this allows doing something like all_user_cluster_commands but with extra filtering on the results.
=> Add a utility method that can be used for implementing helpers like all_user_cluster_commands.

src-electron/generator/helper-endpointconfig.js
`helper-endpointconfig.js` does not generate the proper bytes for strings. It does not take into account the number of bytes to host the string length.
=> Add extra bytes depending on the string types for string attributes

src-electron/db/query-zcl.js
Maintain itemCnt compatibility between withItems and withCount queries.
=> Maintain helper compatibility with itemCnt.

src-electron/db/db-mapping.js, src-electron/db/query-loader.js, src-electron/db/query-zcl.js, src-electron/db/zap-schema.sql, src-electron/generator/helper-zcl.js, src-electron/zcl/zcl-loader-silabs.js, src-shared/types/db-types.ts, test/gen-meta.test.js, test/resource/meta/struct-and-enum-by-cluster.zapt, test/resource/meta/types.xml
- Rename a broken ARRAY_TYPE into IS_ARRAY.
- Add the boolean field struct_contains_array to the struct helper context
- fix https://github.com/project-chip/zap/issues/228
-
=> Clean up the struct IS_ARRAY items.

apack.json, src-electron/generator/helper-zcl.js, test/gen-meta.test.js, test/resource/meta/struct.zapt
- add optional logic for mining the struct items for nested arrays.
=> Identify struct items that contain a struct with an array

src-electron/generator/helper-endpointconfig.js, src-electron/util/types.js
For enum types, get the underlying atomic type and use it for sizing.
For struct types, assume they have to be marked external and just make
sure we generate code that works in that case, throwing if a
struct-typed attribute is not marked external.
=> Fix endpoint_config generation for enum and struct types.

src-electron/generator/helper-endpointconfig.js
We were incorrectly outputting a default value in endpoint_config.h
for external string attributes, as long as there was a nonempty
default value set in the ZAP UI.  The fix is to make sure we don't do
that, because external attributes don't have default values.
The only actual change here is this:
```
if (a.storage == dbEnum.storageOption.external) {
-          typeSize = 0;
-          defaultSize = 0;
+          typeSize = 0
+          defaultSize = 0
+          attributeDefaultValue = null
}
...
-        // literal value is a pain, so just force all strings with nonzero
-        // length to use long defaults.
-        if (defaultSize > 2 || (types.isString(a.type) && a.defaultValue.length > 0)) {
+        // literal value is a pain, so just force all strings with a nonempty
+ …
```
=> Fix default value handling for external string attributes.

package.json, src-electron/generator/helper-zcl.js
In matter, we have event item, which is nullable and fabric index, we need to add the bool variable to check this situation.
=> Add support for nullable fabric scoped event item support

src-electron/validation/validation.js
- https://github.com/project-chip/zap/issues/392
=> fixing attribute page issue

package.json, src-electron/db/query-command.js, src-electron/generator/helper-command.js
Adding if_command_has_response to check if a reponse command exists for a given command
Github#342
=> Adding if_command_has_response for MatterIDL template non determinism

cypress.json, src-electron/validation/validation.js, src/components/ZclAttributeManager.vue, src/layouts/ZclLayout.vue, src/pages/About.vue, src/pages/Preference.vue
- https://github.com/project-chip/zap/issues/286
- https://github.com/project-chip/zap/issues/343
- https://github.com/project-chip/zap/issues/354
- cypress test reenablement
=> Continuous work from TDJ

.github/workflows/sonarcloud.yml, README.md
- clean up the sonarcloud action and add a functioning badge to README.md
=> Add SonarCloud badge properly

.github/workflows/release.yml, package-lock.json
each .zip file should contain an "apack.json" file at the root.
=> Verify release .zip files are valid adapter packs

package.json, src-electron/generator/helper-access.js, src-script/pack-apack-mac.js, test/resource/meta/access.xml, test/resource/meta/access.zapt
Fix for https://github.com/project-chip/zap/issues/436
- added the default_access helper
- added it to the unit tests
=> Add default_access helper.

src-electron/zcl/zcl-loader-silabs.js
Should make it harder for typos to slip in.
=> Add validation of cluster/attribute names in attributeAccessInterfaceAttributes

src-electron/db/db-api.js, src-electron/db/db-mapping.js
https://github.com/project-chip/zap/issues/223
=> saving settings when schema changes 

package.json, src/components/ZclCommandManager.vue
The UI is freezing due to one of our earlier Vue file changes. Reverting them to unblock everyone else.
Github#510
=> Reverting the change which is causing the UI to freeze

src-electron/generator/helper-endpointconfig.js
Updating a commit that should have been updated in PR501
=> Update comment to reflect changes made in PR#501

.github/workflows/zap.yml, package.json, src-electron/main-process/startup.js, src-electron/util/util.js, test/custom-cluster.test.js, test/custom-zcl.test.js, test/test-query.js, test/validation.test.js
Few minor cleanups of the test code, to deal better with the session creation API.
=> Package choice

package.json, src-electron/util/util.js
Emergency fix. Not looking for reviews. Just removing a stray require.
=> Remove stray require that broke binary build.

.husky/pre-commit, package.json, src-script/script-util.js, src-script/zap-update-package-version.js
This PR addresses:
https://github.com/project-chip/zap/issues/488
=> Version automatic handling

package.json, test/gen-matter.test.js, test/gen-template/matter/events.zapt, test/gen-template/matter/gen-test.json, test/test-util.js, zcl-builtin/matter/test-cluster.xml
Unit tests and possible fixes for https://github.com/project-chip/zap/issues/572
=> Event field types

.github/workflows/zap.yml, src/api/renderer_api.js, src/boot/axios.js
- Cleanup the naming of axios global accessor functions.
=> Minor UI improvements.

apack.json, src-electron/main-process/startup.js, src-electron/util/args.ts, src-script/zap-convert.js, test/startup.test.js
file is necessary for Studio / container to work correctly as part of the project upgrade process
BUG: MCUDT-28898
=> create conversion result file during when conversion is invoked

src-electron/generator/helper-zcl.js, test/gen-meta.test.js, test/resource/meta/type-by-cluster.zapt, test/resource/meta/types.xml
Work on: https://github.com/project-chip/zap/issues/582
=> Add helpers to access unused enum values.

Jenkinsfile, package.json, src-script/download-artifact.js
* download from SiliconLabs fork by default
* enable Github token to be passed in via --githubToken
=> creating zap artifact download native binaries

src-electron/generator/helper-zcl.js, test/gen-meta.test.js, test/resource/meta/type-by-cluster.zapt, test/resource/meta/types.xml
https://github.com/project-chip/zap/issues/612
=> Add the format="hex" attribute to the first_unused_enum_value helper.

zcl-builtin/shared/manufacturers.xml
Source document: 
https://groups.csa-iot.org/wg/members-all/document/10905
Output is generated from a script.
=> Update manufacturer XML from latest CSA document.

src-electron/util/util.js, test/query.test.js
The previous PR regarding this issue is out of date. This new one works more appropriately with the rebased updated code.
=> fixing the dirty flag upon startup

.github/workflows/cypress.yml, .github/workflows/mattercypress.yml, .github/workflows/sonarcloud.yml, .github/workflows/zap.yml, test/gen-template/matter3/6.zapt
- clean up some unit tests
- work on upgrading ubuntu container for cypress
=> Clean up cypress

cypress/integration/check_summary/enabled-attributes.spec.js, cypress/integration/check_summary/enabled-clusters.spec.js, package.json, src/components/ZclCreateModifyEndpoint.vue, src/components/ZclEndpointCard.vue, src/layouts/ZclConfiguratorLayout.vue, src/layouts/ZclLayout.vue, src/pages/PreferencePackage.vue, src/store/zap/actions.js, src/store/zap/mutations.js, src/store/zap/state.js
https://github.com/project-chip/zap/issues/556
https://github.com/project-chip/zap/issues/570 
https://github.com/project-chip/zap/issues/557
https://github.com/project-chip/zap/issues/553
https://github.com/project-chip/zap/issues/532
https://github.com/project-chip/zap/issues/527
- Update check_summary tests based on the new UI
=> Resolving UI Issues

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js
This PR is ongoing "keeping Matter in sync" state before the PR of the Matter repo is merged.
=> Keep Matter helpers in sync: 8/12/2022

cypress/integration/check_summary/enabled-clusters.spec.js, cypress/integration/clusters/dimmable-light.spec.js, src/App.vue, src/components/ZclCreateModifyEndpoint.vue, src/components/ZclEndpointCard.vue, src/layouts/ZclConfiguratorLayout.vue, src/layouts/ZclLayout.vue, src/store/zap/actions.js
Fix vue tour cypress problems and add requested features.
=> Fix vue tour cypress problems

src/App.vue, src/components/ZclAttributeManager.vue, src/components/ZclClusterManager.vue, src/components/ZclCommandManager.vue, src/components/ZclCreateModifyEndpoint.vue, src/store/zap/mutations.js, src/store/zap/state.js, src/tutorials/VueTour.vue, src/tutorials/tutorialConfig.json
https://github.com/project-chip/zap/pull/625
=> Fix Vue Tour Issue

src-electron/db/query-package.js, src-electron/rest/user-data.js, src/App.vue, src/components/ZclCreateModifyEndpoint.vue, src/components/ZclDomainClusterView.vue, src/components/ZclEndpointCard.vue, src/store/zap/mutations.js, src/store/zap/state.js, zcl-builtin/matter/zcl.json, zcl-builtin/silabs/zcl.json
- Hide profile id from creating endpoint modal #394 
- Fix showing the endpoint cluster counts #657
=> Hide Profile ID from Matter

cypress/integration/check_summary/enabled-attributes.spec.js, src/components/ZclEndpointCard.vue, src/layouts/ZclLayout.vue, src/store/zap/mutations.js, src/store/zap/state.js
https://github.com/project-chip/zap/issues/711
=> Keep Endpoint Open

src-electron/ui/ui-util.ts
[#696](https://github.com/project-chip/zap/issues/696)
=> Fix Extension Problem

cypress/integration/clusters/cluster-filter.spec.js, cypress/integration/clusters/dimmable-light.spec.js, package-lock.json, package.json, src-electron/rest/static-zcl.js, src/App.vue, src/components/ZclAttributeManager.vue, src/components/ZclAttributeReportingManager.vue, src/components/ZclClusterManager.vue, src/components/ZclClusterView.vue, src/components/ZclCommandManager.vue, src/components/ZclCreateModifyEndpoint.vue, src/components/ZclCustomZclView.vue, src/components/ZclDomainClusterView.vue, src/components/ZclEndpointCard.vue, src/components/ZclEndpointManager.vue, src/layouts/ZclConfiguratorLayout.vue, src/layouts/ZclLayout.vue, src/router/routes.js, src/store/index.js, src/store/zap/actions.js, src/store/zap/mutations.js, src/store/zap/state.js, src/tutorials/VueTour.vue, src/tutorials/tutorialConfig.json
=> Vue tour Final PR

cypress/support/commands.js, src-electron/zcl/zcl-loader.js, src/App.vue, src/pages/ZapConfig.vue
0. Properly shortcut the config page if there is only one of each package type.
=> Fix the issues with the package selection page

.github/workflows/release.yml, .github/workflows/zap.yml, apack.json, jest.config.js, src-electron/generator/generation-engine.js, src-electron/main-process/startup.js, src-electron/util/args.ts
Various bits and pieces that need to come together to make Zap work with an SDK that contains BOTH zigbee and matter subprotocols.
=> Work for multi template and multi zcl SDK.

src-electron/main-process/startup.js, src-electron/zcl/zcl-loader.js
The no-loading-failure switch was not properly implemented. This is a fix for it.
=> Multi ZCL loading failure

apack.json, package.json, src-electron/generator/generation-engine.js, src-electron/main-process/startup.js, src-electron/util/args.ts, test/resource/meta/gen-test.json
https://github.com/project-chip/zap/issues/793
=> Add ability for generator options to carry an appended subdirectory.

src-electron/util/util.js
=> Picking up the first available gen templates json package when one is not mentioned by the zap file

src-electron/generator/matter/app/zap-templates/templates/app/helper.js
- Fix the typo in the camecasing logic.
- Fix typo for real.
=> Fix the failure with camelcasing logic.

src/components/ZclAttributeReportingManager.vue
Fixing the Attribute Reporting columns so mfg code is not shown under Client/Server and vice versa
=> Fixing the Attribute Reporting columns 

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js
Uses the availability yaml for the information instead.
=> Remove hardcoded Darwin API rename maps.

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js
* Makes the compat*NameRemapping functions just rely entirely on the availability rename data instead of doing non-acronym-preserving upcasing.
* Adds compatCommandNameRemapping to handle renamed commands.
* Adds a wasRemoved helper.
* Adds helpers to be able to do boolean logic in "if/unless".
* Adds helpers to be able to do boolean conditions on async values.
=> Add support for removing APIs in Darwin codegen.

src-electron/importexport/export.js
=> do not save Studio integration info inside .zap file

src/layouts/ZclConfiguratorLayout.vue
Light Mode cannot be set to "white"
=> Light mode and Dark mode fix 

src-electron/importexport/import-json.js, test/resource/custom-cluster/custom-cluster-test-1.zap
- Add custom cluster config.
- Properly handle the custom package ID regardless of whether it has been loaded or not before.
=> Fix a problem where custom XML in a .zap file would not load properly.

apack.json, src-electron/db/query-attribute.js, src-electron/generator/helper-zcl.js, test/gen-template/zigbee/zap-tokens-version-2.zapt, test/tokens.test.js
- Extending all_user_cluster_generated_attributes to account for an attribute being a string or not
- Bumping the feature level pointer
- Cleaning up another query to get endpoint Id properly
- JIRA: ZAPP-1036
=> Minor cleanup for zap's attribute token helpers

src-electron/generator/matter/app/zap-templates/common/simulated-clusters/clusters/DiscoveryCommands.js
Device types are 32-bit in the spec.
=> Change deviceType to 32-bit.

src-electron/generator/helper-zcl.js, src-electron/util/types.js, src-script/zap-uitest.js, test/endpoint-config.test.js, test/gen-dotdot.test.js, test/gen-matter-1.test.js, test/gen-test.test.js, test/gen-zigbee-6.test.js, test/script-api.test.js, test/server-with-zcl.test.js
Mostly minor cleanup:
- moving an utility function from helper-zcl to types.js
- removing some hardcoded things
- removing some `.js` from the require statements.
Nothing functional....
=> Minor cleanup.

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js
See project-chip/connectedhomeip#24994
=> Use MTR_DEPRECATED in Darwin availability helper.

apack.json, src-electron/main-process/startup.js
Fixing ZAP upgrade command so the correct files are selected
=> Issue 1010 upgrading

src/layouts/ZclConfiguratorLayout.vue
=> Retrieving new description when switching packages

package.json
This reverts commit 8f073d0162af5201464bf084cb869d430ba36e27.
=> Remove an ill-advised deb and rpm creation removal.

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js
If something gets renamed and the old name is deprecated, then a new thing inside the renamed thing is added (e.g. a new value for an enum that got renamed), we should not generate the new thing combined with the old name.
=> Treat introduction after ancestor deprecation as lack of support for Darwin.

src-electron/rest/file-ops.js, src-electron/rest/initialize.js
=> fix url parsing

src-electron/db/db-api.js, src-electron/db/db-mapping.js, src-electron/db/query-loader.js, src-electron/db/query-package-notification.js, src-electron/db/query-session-notification.js, src-electron/db/zap-schema.sql, src-electron/generator/generation-engine.js, src-electron/generator/template-engine.js, src-electron/ide-integration/studio-rest-api.ts, src-electron/importexport/import-isc.js, src-electron/rest/file-ops.js, src-electron/rest/static-zcl.js, src-electron/rest/user-data.js, src-electron/server/http-server.js, src-electron/util/async-reporting.js, src-electron/util/util.js, src-electron/zcl/zcl-loader-dotdot.js, src-electron/zcl/zcl-loader-silabs.js, src-electron/zcl/zcl-loader.js, src-shared/rest-api.js, src/components/ZclCustomZclView.vue, src/pages/NotificationsPage.vue, src/pages/ZapConfig.vue, test/notification.test.js
Improve ZAP notification system:
1. display package notification to the extension dialog and the notification page
2. display error and warning notifications separately, and change icon correspondingly
3. after importing a new xml extension file, show its package notifications instantly
4. optimize the structure of notification tables in database
5. clean up code and improve code style
=> ZAP Notification System Update

src-script/download-artifact.js, src-script/download-artifact.ts
+ --artifactoryUrl option to download-artifactory, enabling downloads from local artifactory repos.
=> + --artifactoryUrlFeature param option to specify mirror url domain

src-electron/db/query-config.js, src-electron/zcl/zcl-loader-silabs.js
cleaning up storage policy code and fixing issue_1110 in the process https://github.com/project-chip/zap/issues/1110
=> Tagging Attribute Storage Policy properly 

src-electron/db/query-config.js, src-electron/zcl/zcl-loader-silabs.js
This reverts commit 53c1a25cad7fa1628709f40df47f8f93de74a48d.
=> Revert "Tagging Attribute Storage Policy properly  (#1137)"

.github/workflows/release.yml, src-script/zap-uitest.js
restrict chrome to v116 as workaround chrome v117 segment fault bug
https://bugs.chromium.org/p/chromium/issues/detail?id=1483163
=> fix Cypress runtime failure

apack.json
bump feature level for zap. Forgot to do it during the enabled only zap file changes
=> Bump zap's feature level

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js
We treated things with neither "introduced" nor "provisional" annotations as provisional in availabilityHelper(), but isProvisional() returned false for them.  This could lead us to generate non-provisional code (conditioned on isProvisional()) that would try to call into things with provisional availability, which would fail to compile.
The fix is to make isProvisional the source of truth for whether things are provisional, move the "no introduced annotation" check into isProvisional, and factor out the "have provisional annotation" logic so we can keep having the warning when we take the "provisional because not otherwise annotated" codepath.
=> Fix provisional handling for Darwin to be consistent.

src-electron/importexport/import-json.js, src-electron/importexport/import.js, src-electron/main-process/startup.js
=> Adding more logic to pick a better package before picking up the first package in the list of available packages

src/pages/ZapConfig.vue
Show the tootip with path to the json files so that user can distinguish the packages when the name and description are the same
JIRA: ZAPP-1288
=> Show the tootip with path to the json files when session packages need to be selected

README.md
=> Cleaning up ZAP documentation

cypress/e2e/clusters/cluster-filter.cy.js, cypress/e2e/clusters/dimmable-light.cy.js, src/components/ZclAttributeManager.vue, src/components/ZclCreateModifyEndpoint.vue, src/components/ZclDomainClusterView.vue, src/components/ZclEndpointCard.vue, src/util/ui-options.js
=> matter centric UI

src/App.vue
changing session storage depending on what is given from parent iframe
=> Studio V6 Integration

src-electron/validation/validation.js
Issue in https://csamembers.slack.com/archives/C01B01GH64E/p1712782455063339
=> Getting an uncaught error when calling getIntegerFromAttribute with null values

src/pages/ZapConfig.vue
Do not show zap config page when opening .zap files and the packages wihthin it are found
JIRA: ZAPP-1355
=> Do not show zap config page when opening .zap files if there is no need

src-electron/generator/helper-endpointconfig.js, src-electron/util/types.js, test/endpoint-config.test.js, test/gen-matter-4.test.js, test/resource/matter-all-clusters.zap, test/resource/old-matter/chip-types.xml, zcl-builtin/matter/data-model/chip/chip-types.xml, zcl-builtin/matter/data-model/chip/thermostat-cluster.xml
=> Temperature type

src-electron/generator/helper-endpointconfig.js, src-electron/util/types.js, test/endpoint-config.test.js, test/gen-matter-4.test.js, test/resource/matter-all-clusters.zap, test/resource/old-matter/chip-types.xml, zcl-builtin/matter/data-model/chip/chip-types.xml, zcl-builtin/matter/data-model/chip/thermostat-cluster.xml
This reverts commit dc9997e25bcf2563a2f26ed813f62fffcfb6125a.
=> Revert "Temperature type (#1330)"

src-electron/importexport/import-json.js
When importing endpoint types the custom clusters were missing their package ids. Adding them here makes sure that their correct state is picked up during the import
JIRA: ZAPP-1432
=> Custom XML import endpoint type issue when opening .zap file

.gitignore, package-lock.json, src-electron/db/query-package.js, src-electron/generator/generation-engine.js, src-electron/generator/helper-session.js, src-electron/generator/template-engine.js, src-electron/generator/template-util.js
0. Some dependencies cleanup.
1. Matter performance enhancements (mostly from package caching).
=> Matter generation performance improvements

src-electron/generator/helper-endpointconfig.js, src-electron/util/types.js, test/types.test.js
unit test for types.nullStringDefaultValue(a.type)
=> add unit test for issue1356

src/components/ZclAttributeManager.vue
- Solved issue #1375
- Removed virtual-scroll from q-table component in the ZAP GUI
=> Fix glitchy scrolling in attributes by removing virtual-scroll

test/gen-template/matter3/endpoint_config.zapt, zcl-builtin/matter/data-model/chip/matter-devices.xml
- fixing XML to follow CHIP repo changes https://github.com/project-chip/connectedhomeip/pull/34818 
- fixing test to reflect these changes
=> fixing XML and making the corresponding changes to the composition test

docs/api.md, src-electron/db/db-mapping.js, src-electron/db/query-endpoint.js, src-electron/db/query-loader.js, src-electron/rest/endpoint.js, src-shared/db-enum.js, src-shared/rest-api.js, src/App.vue, src/components/ZclClusterManager.vue, src/components/ZclCreateModifyEndpoint.vue, src/components/ZclEndpointCard.vue, src/store/zap/actions.js, src/util/common-mixin.js
**Action to Fetch and Load Root Node Data**
Description:
This PR introduces the loadComposition action to the Vuex store, which performs the following tasks:
Fetch Root Node Data: Retrieves root node data from the server.
Add Endpoint Type: Calls addEndpointType with the fetched data.
Add Endpoint: Calls addEndpoint with the data returned from addEndpointType
=> Endpoint Composition - rootNode on Endpoint 0 (fullFamily)

.github/CODEOWNERS
Adding code owners so that PR's do not go without one of these approvers
=> Adding code owners for ZAP

src-shared/db-enum.js, src/store/zap/actions.js
profileID is constant for Matter
=> adding a profileID constant for matter helper

.husky/pre-commit, docs/zap-cli.md, src-script/generate-cli-documentation.js
=> added script to generate zap-cli documentation as part of pre-commit hook

docs/release.md, src-electron/util/util.js
=> Add versioning documentation for ZAP and Matter.

src-electron/generator/helper-zcl.js, test/custom-matter-xml.test.js, test/gen-template/matter/sdk-ext.zapt
=> baseType not behaving correctly in zcl_commands_with_arguments for custom xml

src-electron/db/db-mapping.js, src-electron/db/query-attribute.js
=> Extending existing helper

test/custom-matter-xml.test.js, test/resource/custom-cluster/matter-custom.xml
- Add command with args in test cluster extension
=> Update tests for Cluster Extensions in Custom XML

src-electron/generator/helper-endpointconfig.js, test/custom-matter-xml.test.js, test/gen-matter-3-1.test.js
=> Bug/fixing min max endpoint config header/zap#1615

docs/api.md, src-electron/db/db-mapping.js, src-electron/db/query-attribute.js, src-electron/db/query-command.js, src-electron/db/query-endpoint-type.js, src-electron/db/query-event.js, src-electron/db/query-session-notification.js, src-electron/db/query-zcl.js, src-electron/rest/user-data.js, src-electron/validation/conformance-checker.js, src-electron/validation/conformance-expression-evaluator.js, src-electron/validation/conformance-xml-parser.js, src-shared/rest-api.js, src/components/ZclAttributeManager.vue, src/components/ZclClusterFeatureManager.vue, src/components/ZclClusterView.vue, src/components/ZclDeviceTypeFeatureManager.vue, src/components/ZclDomainClusterView.vue, src/store/zap/actions.js, src/store/zap/mutations.js, src/store/zap/state.js, src/util/common-mixin.js, src/util/feature-mixin.js, test/feature.test.js, test/importexport.test.js, test/multi-protocol.test.js, test/notification.test.js, test/query.test.js
**New Feature:** Enable users to toggle features in the cluster feature page
**Sync between device type and cluster feature page:**
- sync feature state updates between pages
- ensure the featureMap attribute value is accessible and stays in sync across pages
- move shared logic from Vue files to `feature-mixin.js` for code reuse
**Improve warning system:**
- display warnings and disable feature toggles that will cause other features incorrectly conform
- remove outdated warnings from features related to the toggled feature
- Refine warning messages for clarity
**Testing:**
- add unit tests for new backend functions
- adapt existing tests to updates in function logic and warning message
The PR is large, but all changes are necessary to deliver a functional and bug-free feature page.
=> Cluster Feature Page - Enable feature toggling and sync with device type feature page

src-electron/util/util.js
=> Executing post processing commands synchronously

src-electron/generator/helper-zcl.js, test/zcl-loader.test.js
=> Fitering out atomic bitmaps from zcl_bitmaps just like we do from zcl_enums

src-electron/db/query-data-type.js, src-electron/generator/helper-attribute.js, src-electron/generator/helper-c.js, src-electron/generator/helper-zigbee-zcl.js, src-electron/generator/matter/controller/python/templates/helper.js, src-electron/util/types.js
=> Adding log warnings in helpers when data types cannot be determined
