src-electron/generator/generation-engine.js
src-electron/generator/template-engine.js
src-shared/db-enum.js
test/templates.test.js

This PR allows templates to use the pre-existing **partials** feature of Handlebarjs.
In order to use a partial one would register it in the `gen-templates.json` file, similarly to how **helpers** are registered.
For example one can add to `gen-templates.json`:
```
"partials": [
name: "chip_licence",
path: "chip_licence.zapt"
],
```
And then the partial can be used in the a regular `.zapt` file by doing `{{> chip_licence}}`

Allow templates to use the pre-existing partials feature of Handlebars

---

src-electron/db/query-config.js

The `writable` field of attributes can not be accessed when one uses `{{#user_all_attributes}}`.
This field is useful if one wants to automatically generates methods/wrappers for a given configuration.

Expose the 'writable' field of attributes to templates

---

src-electron/generator/helper-endpointconfig.js
test/endpoint-config.test.js

While generating `endpoint_config.h` the attributes order is sometimes moving around. This is annoying since it creates some useless noises in PRs and it may hides some local changes.
This PR sorts clusters, attributes and commands to make sure the order stay the same between multiple runs.

Sort clusters, commands and attributes in helper-endpointconfig.js

---

src-electron/generator/helper-endpointconfig.js

The function generates defaults for big endian systems.
The function can be (optional) called with:
endian=<'big'|'little'> (default='little')
pointer=<pointer size in bytes> (default=4)
Examples:
#define GENERATED_ATTRIBUTES {{ endpoint_attribute_list endian="big" pointer=4}}
#define GENERATED_ATTRIBUTES {{ endpoint_attribute_list}}
Fixes issue 141

Add support for big endian in function endpoint_attribute_list (#141)

---

src-electron/generator/helper-endpointconfig.js

The values we spit out for long defaults just take the incoming hex
string and dump it into the file.  But for little-endian we need to
reverse the hex bytes for at least integers and floats and enums and
bitmaps... and generally everything that is not strings.

Fix little-endian long default values.

---

src-electron/generator/helper-endpointconfig.js
test/endpoint-config.test.js

emAfLoadAttributeDefaults uses emAfReadOrWriteAttribute to write the
value from defaults into the attr store, and that ends up calling
typeSensitiveMemCopy, which for strings already checks the length and
only copies data up to that length.  That means that for strings we
only need to allocate enough space in the default store for the actual
string length+value, not for all possible values that fit in the
typeSize.

Allocate the mimimum amount of space necessary for string default values

---

src-electron/zcl/zcl-loader-silabs.js

This adds a "defaultReportable" property to the metadata file and uses
that to decide whether the "reportable" XML attribute defaults to true
of false when it's not set.

Add a way to configure the default reportability of attributes.

---

src-electron/db/query-zcl.js

Field identifier was being used in the sort order but not actually
present in the select part of the query. It needs to be there so the
field identifier can be used in further processing.
Tested by running Matter cert tests.

Add field identifier to struct item queries

---

src-electron/generator/helper-endpointconfig.js
src-electron/util/types.js
test/endpoint-config.test.js

We should generate these for all writable attributes that have a min
or max specified in the XML.
The test change makes sure we are able to actually query size
information for our types properly in the test.  This also allows
removing some workarounds for missing atomic type info.

Fix generation of min/max constraints.

---

src-electron/rest/user-data.js
src-electron/validation/validation.js
test/validation.test.js

Negative integer can not be used as defaults, since the `-` character is not taken into account.
Also ` ` is a valid `float` based on the current regex. I'm not sure if that's an expected assertion or not.
* Make sure that `-` is taken into account
* Update the `float` regex to not allow ` `, nor `.9` nor `5.` but only `1`or `1.2`.
Additionally `endpointTypeIdList` is not defined into the request body for me when I try to edit an attribute.
Since `endpointTypeId` is defined I changed the code to understand both, but I suspect that there is some other root issue.
#Fixes 327

Allow negative defaults for attributes

---

src-electron/zcl/zcl-loader-silabs.js

Matter field ids start at 0, not 1, but the defaulting was defaulting
to starting at 1.
The new setup defaults the first field to 0, and every following field
to 1 more than the previous one (which might have an explicitly
specified field id).

Fix field id defaulting for Matter.

---

src-electron/db/query-impexp.js
src-electron/db/query-loader.js
src-electron/db/zap-schema.sql
src-electron/zcl/zcl-loader-silabs.js
src-shared/db-enum.js

Some SDK implementations want to force some specific storage policy
for attributes depending on implementation decisions.  Add some
mechanisms for doing that:
* Add a way to force all lists to have an "attributeAccessInterface"
storage policy.
* Add a way to provide a map of attributes that have an
"attributeAccessInterface" storage policy.
For now this policy is mapped to "External" storage for endpoint
attributes, but later on I want to add another value to that enum and
use it instead of "External", because there are some optimizations we
can do for "attributeAccessInterface" that we can't do for things that
are just "External".

Add a storage policy for attributes.

---

src-electron/generator/helper-endpointconfig.js

This is required by https://github.com/project-chip/connectedhomeip/issues/10780
We need to get the list of commands under specific cluster under specific enqpoint.

Add endpointId and commands field to endpoint.clusters

---

src-electron/generator/helper-zcl.js

This is a temporary plan to fix the behavior for is_fabric_scoped_event.
At the end of the day, we need a flag in XML to mark if the struct is a fabric scoped event / field instead of checking the fields.

Do not set is_fabric_scoped_event for nullable fabric index field

---

src-electron/generator/helper-endpointconfig.js
test/endpoint-config.test.js
test/tokens.test.js

These are not used for anything in Matter and are just taking up
space.

Stop generating command and attribute lists for client clusters.

---

src-electron/db/db-mapping.js
src-electron/db/query-command.js
test/zcl-loader-consecutive.test.js

Matter commands now all specify explicit response="" in XML, so
we can do all matching by RESPONSE_NAME.
Also, expose RESPONSE_NAME in command queries so consumers can use it,
now that it's reliable.

Remove the response-matching heuristic.

---

.github/workflows/cypress.yml
.github/workflows/release.yml
.github/workflows/sonarcloud.yml
.github/workflows/zap.yml
README.md

- rename the badges
- remove cypress and back-end tests from the main release workflow

Rename the badges and remove extensive testing from the release build.

---

src-electron/generator/helper-endpointconfig.js

The Matter stack does not expect these to have metadata, and in fact
will behave incorrectly if they do.

Stop emitting attribute metadata for global list attributes in Matter.

---

src-electron/util/types.js

The passed-in object does not have a "label" property, it has a "name"
property.

Fix error logging in sizeTypeAttribute.

---

src-electron/generator/helper-endpointconfig.js

Stop (implicitly) assuming that unknown storage types mean RAM.

Sanity check the storage type in endpoint_config.

---

package.json
src-script/script-util.js

- This makes sure to throw a signal error when the code is null such …
- Verified that now zap regen errors out and gives a the following when it runs out of memory: 👎 Program node exited with signal code: SIGABRT
- ZAP#468

Check for an involuntary signal error when the voluntary code error thrown is null

---

package.json
src-electron/db/query-endpoint.js
src-electron/generator/helper-endpointconfig.js

Per spec (Spec 7.17.3.1, 7.17.3.2), the GeneratedCommandList are the commands that in response to another command in AcceptedCommandList
This PR will include a "responseName" in the cluster info in endpoint config, to generate the above attributes correctly.

Add responseName field to clusters in endpoint config

---

package-lock.json
package.json

Dependabot helpfully upgraded sqlite, and this was ok on ubuntu 20.
Ubuntu 18 however has weird problems. Because we still support ubuntu 18, I'm downgrading this update back to how it was before.

Downgrade sqlite back to 5.0.2, as 5.0.3 has problems with ubuntu 18.

---

src-electron/generator/helper-endpointconfig.js

We were creating nonsense mask values (like setting "incoming_server"
for an optional server-generated command if "incoming" happened to be
set in the .zap file for some reason for the server cluster side).

Fix command mask in endpoint config.

---

.github/workflows/zap.yml
Jenkinsfile
package.json
zcl-builtin/shared/script/validate

Turns out that Matter XML files are completely non-compliant against zap.xsd schema.
I am temporarily turning off XML validation for Matter files until this is sorted out. Zap can still load them, since zap does not require schema compliance, it simply does a best attempt load, regardless of whether schema matches or not.

Skip Matter validation until XML is sorted out.

---

src-electron/generator/helper-endpointconfig.js

We were claiming a command is "incoming" or "outgoing" even if it was
not enabled, if it was mandatory.
This led consumers that looked at that state to be out of sync with
other consumers that just looked at the actual enabled state.
This PR makes sure we treat the actual enabled state, not theoretical
mandatory-or-not status, as the source of truth.

More fixes for command masks in endpoint config.

---

package.json
src-electron/util/args.ts
src-electron/util/env.ts

If JENKINS_HOME environment variable is present, then automatically assume ZAP_TEMPSTATE and ZAP_SKIP_POST_GENERATION.
This is to prevent setting that up in millions of Jenkins jobs, since on CI, these should always be assumed, as it guarantees isolation and decouplement from development environment.
Idea is, that the different configurations for zap in CI, compared to development environment, can be auto-detected, instead of pestering build engineers with setting tons of environment variables.
We might want to do something like this for github actions as well, but let's do this one thing at a time.

Honor JENKINS_HOME or --jenkins argument

---

package-lock.json
package.json
src-electron/main-process/main.ts
src-electron/main-process/startup.js
src-electron/ui/main-ui.ts
src-electron/util/util.js

Fix the problem where electron and node startups did not share the single instance logic.
https://github.com/project-chip/zap/issues/514
0. Bring in an external single-instance package, that is not electron specific.
1. Add a util method.
2. Converge both headless and UI startup through the same logic.

Fix the "zap stop" functionality.

---

src-script/build-spa.js
src-script/script-util.js
src-script/zap-convert.js
src-script/zap-generate.js
src-script/zap-start.js
src-script/zap-versionstamp.js

This solves a problem, that after every zap action (generate, analyze, run UI, etc), the package.json ends up in a dirty state, because scripts insert a valid version instead of a 0.0.0.
After this change, the version is cleaned back to the committed state: 0.0.0, so anyone relying on cleanliness of submodule will be ok.
We can revisit this if we ever revisit zap versioning scheme.

Add the end-of-run cleanup action to set package.json back to 0.0.0

---

apack.json
package.json
src-electron/main-process/main.ts
src-electron/main-process/startup.js
src-electron/server/ipc-server.ts
src-electron/ui/main-ui.ts

1. Make the IPC socket reused the same way as the lock instance socket is reused.
2. Cleanup the code a bit.
3. Allow IDE to pick up tests by increasing feature level.
4. By default load all the data.
5. Fix the problem with hanging in the client generation case.

Clean up server-mode for concurrent use

---

src-electron/main-process/startup.js

There was a "can't find uiEnableFunction" error if you start the UI.

Fix a problem that got created in recent PR.

---

src-electron/db/query-zcl.js
src-electron/generator/helper-zcl.js
src-electron/zcl/zcl-loader-silabs.js
test/gen-meta.test.js
test/resource/meta/access.zapt
test/resource/meta/struct.zapt
test/resource/meta/test1.xml
test/resource/meta/types.xml

1) Remove struct_is_fabric_scoped and event_is_fabric_scoped now that we have
isFabricScoped/isFabricSensitive on those objects.  Add the relevant XML
attributes instead of trying to guess based on fields.
2) Remove event_fabric_idx_field and struct_fabric_idx_field, since we are no
longer guessing based on fields.
3) Synthesize the relevant struct item or event field with the right name, type,
field id, per spec, if the struct is fabric-scoped or the event is
fabric-sensitive.
This is a hard requirement for implementing Leave events properly for Matter:
those have a fabric_idx field but are _not_ fabric-scoped.

Fix FabricIndex handling in structs and events.

---

src-electron/util/bin.ts
test/bin.test.js

Long strings store their length in 2 bytes at the front of the string, with the
bytes being a little-endian representation of the string length.
But the endpoint config output was spitting out the length as big-endian, not
little-endian.  This caused things to be pretty confused and led to buffer
overruns trying to read data that was not there.

Fix default values for long strings.

---

.github/workflows/zap.yml
apack.json
docs/sdk-integration.md
package.json
src-electron/main-process/startup.js
src-electron/util/args.ts
src-electron/util/env.ts
src-script/gen-log-parse
src-script/script-util.js
src-script/zap-generate.js
src-script/zap-start.js
test/resource/meta/sdk.json
test/resource/test-meta.zap

This addresses some Matter issues with regeneration, and will make Matter regen both faster and more reliable.
It goes hand in hand with a commit on Matter SDK, that includes the sdk.json file and will come later. The infrastructure for it is here now though.

SDK-wide regen via sdk.json file

---

apack.json
src-electron/zcl/zcl-loader-silabs.js
test/gen-meta.test.js
test/resource/meta/zcl.json
zcl-builtin/matter/zcl.json

This addresses:
https://github.com/project-chip/zap/issues/629
It adds data-driven mechanism for fabric index field automatic creation.
** NOTE: this should be merged only after https://github.com/project-chip/connectedhomeip/pull/21273 is merged. **

Fabric index cleanup

---

src-electron/generator/matter/app/zap-templates/templates/app/helper.js

This is a followup for 9ffb3b7cbbe361a377971621cd50b2d9001faf51

Fix asUpperCamelCase so it does fails for words of size 1 (followup)

---

src-electron/server/ipc-server.ts

fix JSON START/END message not sending on windows.
node-ipc was having a hard time creating the socket due to not recognizing the path as valid.
BUG: ZAPP-969

fix zap server startup error on windows

---

src-electron/db/query-package.js
src-electron/importexport/import-json.js
test/gen-zigbee-2.test.js
test/resource/zap-file-with-custom-xml.zap

- This solves the issue of zap generation when the saved zap file already has the custom xml reference and then generation is performed on it using cli
- Loading the main/standard gen template and zcl xml packages before the custom xml packages such that custom xml and clusters extensions within custom xml are loaded properly
- Fixing a query in query-package.js
- Adding tests for the above behavior by creating a zap file which has a reference to a custom xml. Testing generation of zap file and adding more tests for xml removal and generating again
- JIRA: ZAPP-971

Changes to resolve the custom xml generation/loading issue with zap's cli generation.

---

apack.json
src-electron/generator/helper-zigbee-zcl.js
src-electron/zcl/zcl-loader-silabs.js

- Adding additional options to zcl_command_argument_type_to_cli_data_type_util function such that it can account for the the isOptional argument to return the precise CLI command argument
- The xml mentions optional=1 for the command arguments. Therefore accounting for that in the zcl-loader-silabs.js
- JIRA: EMZIGBEE-10318

Fixing the command argument optional attribute loading and fixing the zcl cli helper to take that into account

---

.github/workflows/cypress.yml
.github/workflows/mattercypress.yml
.github/workflows/release.yml
.github/workflows/sonarcloud.yml
.github/workflows/zap.yml

When internal PR depend on a specific branch, the build should be kicked off automatically during branch creation instead of requiring a manual kick off. Many users do not know it is required.

trigger on push/pr for all branches.

---

cypress/integration/devtools/devtools.spec.js
src-electron/db/db-mapping.js
src-electron/db/query-notification.js
src-electron/db/zap-schema.sql
src-electron/importexport/import-isc.js
src-electron/rest/user-data.js
src-shared/db-enum.js
src-shared/rend-api.js
src-shared/rest-api.js
src/layouts/ZclConfiguratorLayout.vue
src/layouts/ZclLayout.vue
src/pages/Notifications.vue
src/router/routes.js

This is a Draft PR for the notification framework.
TODO:
1. **Decide how the querying of SESSION_NOTICE table will be implemented.**
_OPTIONS:_
A. Notifications should be able to be triggered at any moment. Therefore, it would make sense to have interval polling          which constantly checks for new notifications.  This is not in the PR but I have this working locally. Although this code is out of date, here is an example of how it might work https://github.com/project-chip/zap/commit/57d9486034af18b16d203a9e9c432212fdb6348e
B. If notifications are not able to be triggered at any moment and are specific for importing and exporting .zap files then there could be a function which queries the SESSION_NOTICE table after importing. This way there would be no need for polling. Basically, the …

Notification system (RENOP)

---

apack.json
src-electron/db/db-mapping.js
src-electron/generator/helper-zcl.js

- Helper for getting size of zcl type
- If helpers to check sign and size of data type

Adding helpers for zcl data types

---

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

We need to do some backwards-compat bits to handle TestCluster being renamed to UnitTesting.

Add support for backwards-compat shims for cluster renames on Darwin.

---

src-electron/importexport/import-json.js

This fixes the problem where pre-check (zaptest) on the Zigbee stack failed with the old .zap files
that had incorrect package information inside them. While those files are in error, we
do promise backwards compatibility, and that includes backwards compatibility with 
zap files created prior to proper implementation of package recording.

Allow failures in non-strict autoloading, to accomodate for legacy files.

---

apack.json
src-electron/generator/overridable.js
src-electron/util/zcl-util.js

- adding no_warning option in overridable.atomicType so that /* TYPE WARNING: */ message does not get generated because if this helper is used within a comments section of the code then compiler will throw an error
- Bumping the feature level
- JIRA: ZAPP-991

Providing a mechanism in Overridable to prevent additional comments

---

package.json
src-electron/generator/generation-engine.js
src-electron/main-process/startup.js
src-electron/util/args.ts
src-electron/util/env.ts

- Use 'ignore' as default packageMatch + add generation log.
- Actual switch to 'ignore'.
- Fix fuzzy as a package match for genmeta2.

Switch to Matter-friendly package matching.

---

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

clang-format doesn't deal with missing newlines in some places well: it inserts them, but not in all the places it needs to, so we end up in a situation where running it multiple times produces different output than running it once.
Work around by just manually inserting a newline.

Work around clang-format bug.

---

jest.config.js
src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

Also adds a way to check whether a field in a container has been renamed.

Expose old names directly for Darwin codegen.

---

package.json
src-script/script-util.js

- Add temporary target used to test with local fork of pkg.
- Honor ZAP_SKIP_REAL_VERSION environment variable.

Allow version stamp skipping and local pkg install.

---

src-electron/generator/matter/app/zap-templates/templates/app/helper.js
src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

Move it to a YAML resource file provided by the template instead.

Move the weakly typed enum list out of ZAP code.

---

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

So if a cluster is removed, everything in that cluster should be considered removed.

Removed annotation for Darwin should remove everything in the container.

---

src-electron/generator/helper-endpointconfig.js
test/endpoint-config.test.js

Reordering of struct EmberAfAttributeMetadata members
On the example of lighting-app, memory savings are:
Was:
00000000 00004336 r (anonymous namespace)::generatedAttributes
After changes:
00000000 00003252 r (anonymous namespace)::generatedAttributes
As calculated 1/4 is saved or 1084 bytes.
https://github.com/project-chip/connectedhomeip/issues/23720

Reordering of struct EmberAfAttributeMetadata members

---

src-electron/db/query-endpoint-type.js
src-electron/generator/helper-endpointconfig.js
src-electron/generator/matter/app/zap-templates/templates/app/helper.js

There were two bugs:
1) asMEI produced incorrect output if the manufacturer code was high enough that
the high bit in it was set, due to ending up with negative numbers.
2) chip_server_clusters for some reason used mfgCode, not manufacturerCode
(which almost everything else uses).

Fix handling of manufacturerCode in various places.

---

src-electron/generator/matter/app/zap-templates/common/ClustersHelper.js

It would get things wrong if two different clusters had a response command with the same name.

Fix response determination in ClustersHelper.

---

src-electron/util/util.js
src-shared/db-enum.js

This allows variables like $CHIP_ROOT to be used, which is needed when the chip codebase is independent to the repository the zap file is in.
Throw an error when any variable used fails resolving.
PR implementing this in connectedhomeip.git/scripts/generate.py: https://github.com/project-chip/connectedhomeip/pull/24482

Add a resolveEnvVars option to .zap package.pathRelativity

---

src-electron/generator/matter/app/zap-templates/common/simulated-clusters/clusters/CommissionerCommands.js

The `matter` YAML tests exposes `commissionerNodeId` as an internal variable. This PR is the first step to expose it as a pseudo-clusters method instead.

Add CommissionerCommands::GetCommissionerNodeId

---

apack.json
src-electron/db/query-loader.js
src-electron/zcl/zcl-loader-silabs.js

- These changes allow data types having the same name belonging to different clusters to be loaded.
- The queries have been modified such that cluster specific data types are searched for and inserted into the DB. If not found then generic data types which do not specifically belong to a cluster are used.
- The changes have been applied to enums, bitmaps and structs and then corresponding changes have been made to enum_items, bitmap_fields and struct_items
- Extracting the cluster codes correctly in zcl-loader-silabs.js such that it can be used in query-loader.js
- Updating the requiredFeatureLevel such that the stacks can use the new feature level if templates change according to these changes
- Github: ZAP#906

Allowing Data types having the same name to be loaded into the DB

---

apack.json
src-electron/db/db-mapping.js
src-electron/db/query-attribute.js
src-electron/db/query-cluster.js
src-electron/generator/helper-tokens.js
src-electron/generator/helper-zcl.js
test/gen-template/zigbee/gen-templates.json
test/gen-template/zigbee/zap-tokens-version-2.zapt
test/test-util.js
test/tokens.test.js

- Updated helper-tokens with token_attributes, token_attribute_clusters and token_attribute_endpoints helpers which can be used by the generation templates.
- Deprecated tokens_context and token_next helpers which were giving incomplete and wrong generation results
- Updated some existing block helpers in helper-zcl with token information to help with generation
- Added the queries for token helpers in query-attribute and query-cluster files
- Updated dbMapping with endpointTypeClusterExtended and endpointTypeAttributeExtended such that map functions can be used in a generic way
- JIRA: ZAPP-1036

Create token helpers for generating the token files using ZAP

---

src-electron/generator/matter/app/zap-templates/templates/app/helper.js

As discussed on https://github.com/project-chip/connectedhomeip/pull/24844, we should have some type of callback that is able to called to shutdown pending timers on clusters that are being torn down.
This code adds `MatterXXClusterServerShutdownCallback` in the same way zap generates callbacks to `emberAfXXClusterServerInitCallback`
@bzbarsky-apple @andy31415

new: support for cluster shutdown functions

---

src-electron/generator/matter/app/zap-templates/common/simulated-clusters/clusters/CommissionerCommands.js

The matter SDK needs to modify `CommissionerCommands:PairWithCode` to takes an extra optional argument.

Add CommissionerCommands::PairWithCode discoverOnce optional argument

---

src-electron/generator/matter/app/zap-templates/templates/app/helper.js
src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js
src-electron/generator/template-engine.js
test/helper-api-baseline.json

- Throwing a warning in the notifications page of the zap UI instead of throwing an error in template-engine such that we backwards compatibility can be maintained
- Changes to helper.js files have been made to fall back to old way of implementation in the case of global.resource([key]) not finding the data required
- Github: ZAP#941, ZAP#942

Fix backwards compatibility for recent zap changes

---

src-electron/generator/helper-endpointconfig.js
test/endpoint-config.test.js

- Changing the default order of endpoint_attribute_list to what it was such that previously released SDKs continue to build their apps seamlessly. Newer templates can mention this order within the template itself
- fixing the endpoint_config test to default to old order
- JIRA: ZAPP-1081

Backwards Compatibility Fix

---

.github/workflows/release.yml

Use an absolute path when testing zap generation: we likely want ZAP_INSTALL_PATH to be absolute and not depend on PWD when chip runs things (chip scripts may change their pwd to the build directory).

Make the zap install path absolute for CI

---

src-electron/generator/helper-endpointconfig.js
src-electron/generator/matter/app/zap-templates/templates/app/helper.js

* "clusterSize:" had a stray ':' that was causing generation to produce invalidoutput.
* The old code had things indented sanely, and this is just restoring that.
* There was no detection of unknown tokens, which would have quickly caught the "clusterSize" problem.

Fix cluster list generation.

---

src-electron/db/query-attribute.js
test/tokens.test.js

The token attributes are being set in the following order:
For Standard attributes:
- All singleton attributes
- All non singleton attributes
- Both of the above are followed by subsequent ordering of cluster mfg code, attribute mfg code, endpoint identifier(smallest endpoint identifier for singleton), cluster code, attribute code
Configuring the tests according to the above order

Set the order of token attributes for minimal diff upon resetting token config

---

src-electron/db/query-attribute.js

7x speed up on zap-config.h generation speed
machine: mac x86 2.6 GHz 6-Core Intel Core i7
Before:
PASS  test/gen-zigbee-9.test.js (91.223 s)
✓ Basic gen template parsing and generation (18 ms)
✓ Validate package loading (1 ms)
✓ Load the zap file: /Users/jiteng/repo/zap/test/resource/full-th.zap (1149 ms)
✓ Generate "zap-cluster-command-parser.h" (196 ms)
✓ Generate "zap-print.h" (14 ms)
✓ Generate "zap-id.h" (402 ms)
✓ Generate "zap-event.c" (111 ms)
✓ Generate "zap-enabled-incoming-commands.h" (41 ms)
✓ Generate "zap-event.h" (746 ms)
✓ Generate "zap-config.h" (72763 ms)
✓ Generate "zap-type.h" (223 ms)
✓ Generate "zap-tokens.h" (574 ms)
✓ Generate "zap-cli.c" (3542 ms)
✓ Generate "zap-command.h" (1161 ms)
✓ Generate "zap-command-structs.h" (448 ms)
✓ Generate …

improve zap-config.h generation speed by 7x

---

docs/api.md
src-electron/db/db-mapping.js
src-electron/db/query-attribute.js
src-electron/db/query-bitmap.js
src-electron/db/query-data-type.js
src-electron/db/query-enum.js
src-electron/db/query-number.js
src-electron/db/query-struct.js
src-electron/db/query-util.js
src-electron/db/query-zcl.js
src-electron/generator/helper-session.js
src-electron/generator/helper-zcl.js
src-electron/generator/matter/app/zap-templates/templates/chip/helper.js
src-electron/generator/matter/controller/java/templates/helper.js
src-electron/generator/matter/controller/python/templates/helper.js
src-electron/util/zcl-util.js
test/gen-matter-4.test.js
test/gen-template/matter3/miscellaneous_helper_tests.zapt
test/gen-template/matter3/t.json
test/test-util.js

- chip_server_cluster_attributes is returning server attributes which are not actually enabled because the server side cluster is disabled.
- The reason chip_server_cluster_attributes is picking the server side attributes which are not enabled is because those are enabled in the .zap file(Which is the case for saving user selections and ease of use). However the helper is not actually checking if the cluster is enabled as well.
- all_user_cluster_attributes_irrespective_of_manufacturing_specification is solving this issue correctly and actually only showing attributes which are truly enabled.
- Github: ZAP#898

Adding to zcl_attributes_server and enabled_attributes_for_cluster_and_side helpers to replace chip_server_cluster_attributes

---

src-electron/generator/matter/controller/java/templates/helper.js

Adding exceptions to if_basic_attribute
Github: ZAP#898

Adding exceptions to if_basic_attribute

---

src-electron/generator/helper-session.js
src-electron/generator/matter/app/zap-templates/templates/chip/helper.js

Deprecating the matter stateful helpers with stateless ones
Github: ZAP#682

Deprecating the matter stateful helpers

---

src-electron/main-process/startup.js

When Upgrading a Zigbee or Matter App there is one error message 
```Failed to run upgrade apack_zclConfigurator UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "You need to specify at least one zap file."```
This message is not because of the ZAP upgrade process but rather because the ZAP source code checks the .ZAP file for upgrades before finding the .ZAP file in its folder. The result is that even if there is a .zap file in the config folder, the user will be told they need to specify a .zap file.
In order to fix this, changed the order of operations so the code gathers the files before checking the files.
After …

Uccli upgrade fix

---

src-electron/generator/matter/app/zap-templates/templates/chip/helper.js

deprecating chip_cluster_specific_structs and chip_shared_structs

---

src-electron/ide-integration/studio-rest-api.ts
src-electron/rest/file-ops.js
src-electron/server/http-server.js
src/boot/ws.js
src/layouts/ZclConfiguratorLayout.vue

When loading a ZAP file with a feature version that is higher than your currently installed ZAP, the message is incorrectly handled. This PR fixes the reference so it displays the actual error and not "undefined" as described here https://github.com/project-chip/zap/issues/995.

Error message fix for loading new ZAP file

---

src-electron/db/db-mapping.js
src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

This supports marking this as "provisional", which unlike "removed" can be overridden by a later "introduced".

Add isSupported helper for Darwin.

---

src-electron/db/query-zcl.js
src-electron/generator/helper-zcl.js
test/gen-matter-4.test.js
test/gen-template/matter3/miscellaneous_helper_tests.zapt
zcl-builtin/matter/data-model/chip/access-control-cluster.xml

- Add zcl_struct_items_by_struct_and_cluster_name helper for retrieving struct items based on struct and cluster name in helper-zcl.js
- Updating selectAllStructItemsByStructName to handle cluster name as well
- Updating the xml for TargetStruct such that it is now present in binding and access control clusters
- Adding a test to make sure the right struct items are generated based on cluster names
- Github: ZAP#916

Adding struct item helper based on struct and cluster name

---

package.json

deb/rpm distribution is not widely use and there is no current resource dedicated in maintaining those packages. it is removed until working versions are created again.

remove deb/rpm release distribution

---

apack.json
src-electron/main-process/startup.js
src-electron/util/args.ts

There was a hard-coded reference to `zcl_config.zap` in the "zap file upgrading" entry point, because ZIgbee SDK happens to use those files. Matter was not happy.
The entry point was updated to accomodate for any name in any directory...

Remove the references to zcl_config.zap from the apack.json.

---

apack.json

This is accomodating for a bug in a certain driving software that
wants to execute zap as a part of the upgrade, yet there is no way
to configure it in a way where you tell it "there is nothing to upgrade"
without even calling zap.
So it calls zap, and then errors with timeouts. The quick no-op
is here to essentially make that software back off quickly and move
on.
There is no changes whatsoever to actual zap functionality.

Swap out the ugprade action that does nothing with a genuine --noop.

---

src-electron/ui/menu.js
src-electron/ui/window.ts

After fixing, Windows users can save ZAP projects properly to a local file and see the menu bar at the top of ZAP when do `npm run zap`.
Fix issue #764

Fix Windows file save bug & menu bug

---

src/components/ZclAttributeReportingManager.vue

Fix issue #996 
The issue is about when initializing the attribute reporting page, some attributes should have their enabled button turned on, but they are actually turned off.
After the fix, if an attribute has mandatory or suggested reporting policy, then its radio button will be turned on automatically when the page is initialized.

Fix button state issue in attribute reporting page

---

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

This lets us add a "swiftUnavailable" section to the availability YAML to annotate deprecated things that should be marked NS_SWIFT_UNAVAILABLE.

Add NS_SWIFT_UNAVAILABLE annotations to Darwin availability bits.

---

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

This is going to lead to codegen changes for Matter.  Those changes are expected; there are also Matter-side changes that need to happen once isProvisional exists.

Stop treating provisional as implying disabled for Darwin.

---

src-electron/ide-integration/studio-rest-api.ts
src/pages/ZapConfig.vue

user can submit bypassing incorrectly configured config page - working on proper fix
also, the user does not need to have a gen-template.json file
finally, deleting error message because we have a ticket for it and it should not print over and over again
tested with reproducer https://github.com/project-chip/zap/issues/1080 in this ticket

workaround for issue_1080

---

src-electron/db/query-impexp.js

populating device code and device name correctly when importing from old .zap files
Github: ZAP#862

Fix old zap file imports for device types

---

test/gen-template/dotdot/addon-helper.js

The `asCleanSymbol` function in the `addon-helper.js` file has a problem in that only up to 2 spaces can be replaced with underscores.
- `asSnakeCaseLower('Week Day Access Schedules')` -> `'week_day_access _schedules'`
This change modifies the `asCleanSymbol` function to replace all spaces with underscores.
- `asSnakeCaseLower('Week Day Access Schedules')` -> `'week_day_access_schedules'`

Fix replace bug of asCleanSymbol in addon-helper

---

apack.json
quasar.conf.js
src-shared/db-enum.js
src/App.vue
src/components/ZCLToolbar.vue
src/components/ZclClusterManager.vue
src/components/ZclClusterView.vue
src/components/ZclCreateModifyEndpoint.vue
src/components/ZclEndpointCard.vue

- Includes Core specification
- Includes Device Library Specification
- Includes Application cluster specification
- JIRA: ZAPP-1104

Adding Matter and Zigbee documentation to the ZAP tool

---

src-electron/db/db-mapping.js
src-electron/db/query-impexp.js

Fixing the non-determinism of endpoint type refs and device type refs in the .zap files by removing it for device type refs and using the index for endpoint type id instead of the primary keys of their corresponding tables since they are non deterministic

Fix non-determinism in the .zap file for endpointType and device type ids

---

src-electron/generator/matter/app/zap-templates/common/attributes/Accessors.js

See https://github.com/project-chip/connectedhomeip/issues/28357: we are not mutating the actual value the caller will observe.
Note: This is expected to change Matter codegen.  The previous codegen was broken.

Fix accessor signatures for string/octstr attributes.

---

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

If a global attribute is marked provisional, that should auto-mark it as provisional for all clusters without requiring explicit annotations to that effect.

Improve handling for provisional global attributes in Darwin codegen.

---

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

This lets us control exactly what things expand to via our defines header.

Output MTR_AVAILABLE, not API_AVAILABLE for Darwin codegen.

---

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

We were not declaring "error", so ended up throwing an "undeclared variable" exception, not the actual exception we were trying to throw.

Fix error-handling for unknown type in asObjectiveCNumberType.

---

.github/workflows/release.yml
src-script/pack-cli.js

NOTE: for zap-cli binary, the mac x86 binary is used for the arch64 package
as a workaround since pkg, the build tool, does not official support for mac-arch64 yet.

create mac arch64 package.

---

src-electron/db/query-cluster.js
src-electron/db/query-config.js
src-electron/db/query-impexp.js
src-electron/db/query-package.js
src-electron/importexport/import-json.js
src-electron/upgrade/upgrade.js
src-electron/zcl/zcl-loader-silabs.js
test/gen-matter-4.test.js
test/tokens.test.js

handling global attributes per cluster 
https://github.com/project-chip/zap/issues/543

handling global attributes per cluster

---

src-electron/generator/matter/app/zap-templates/templates/app/helper.js

zapTypeToClusterObjectType needs to be consistent with the actual types we generate for cluster objects, and it was producing different output for a struct (or event) which had an all-caps name.

Fix zapTypeToClusterObjectType to have correct output for acronyms.

---

src-electron/db/query-package-notification.js
src-electron/importexport/import-json.js
src-electron/zcl/zcl-loader-silabs.js

- The changes to import-json.js allows the ZAP UI to load instead of throwing an error and locking ZAP.
- Now the error message appears in the ZAP notification's pane so that the user can see a detailed error and act upon it
- Minor cleanup
- JIRA: ZAPP-1148

Allow the ZAP UI to load when a custom xml file is not found instead of throwing an error

---

src-electron/importexport/export.js

Zap mistakenly output `"log": []` into the zap output if log was empty. It is no longer doing that.

If log is empty, do not write it out into the zap file.

---

src/components/ZclAttributeManager.vue

This PR addresses the issue of attributes that are manually changed to External Storage.
If an attribute is set to External Storage at any moment then the default value will be uneditable.
Additionally, in this case the value should be set to null to avoid user error.

Default disable

---

.github/workflows/matter.yml

Code-generated tests have been removed, so there is no longer a "tests" type for zap_regen_all.py.

Fix Matter codegen test.

---

apack.json
src-electron/db/query-config.js
src-electron/rest/endpoint.js
src-electron/rest/user-data.js
src-shared/rest-api.js
src/components/ZclCreateModifyEndpoint.vue
src/store/zap/actions.js
src/store/zap/mutations.js

Bug fix:
When user edits Endpoint it must return Endpoint Identifier to the GUI and not the database reference

Bug fix editing parent endpoints

---

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

This change in helper.js asObjectiveCClass function, enables the use of an optional struct type prefix for ZAP generation. It’s needed to generate Objective-C class names with the “MC” prefix, which are specific to Matter Casting, tv-casting-app example. 
**Change summary**
**Note:** Most of the changes are whitespace changes made by the git commit.
1.	Added a check for an struct type prefix configuration through the options object. If the new structTypePrefix option is not specified, the default “MTR” struct type prefix will be used in the  asObjectiveCClass ZAP helper function.
2.	Specifying structTypePrefix="MC" in {{asObjectiveCClass type cluster structTypePrefix="MC"}} will generate a struct type with the “MC” prefix.
**Testing**
Verified and tested ZAP generation locally using …

ZAP generation js helper

---

src-electron/generator/helper-endpointconfig.js
test/gen-matter-4.test.js

change Parent Endpoint helper to return kInvalidEndpointId which is a constant in Matter SDK

change Parent Endpoint helper to return kInvalidEndpointId 

---

cypress/e2e/clusters/cluster-filter.cy.js
cypress/e2e/clusters/cluster-multiple-search.cy.js
cypress/e2e/clusters/cluster-search.cy.js
src/components/ZclClusterManager.vue
src/store/zap/mutations.js

Fix the issue on the UI when using text filtering neither the close all button nor the clusters itself couldn't open and close the clusters correctly.

Fix UI cluster closing issues while using text based filtering

---

src-electron/db/query-attribute.js
src-electron/db/query-config.js

Fixing bug when selecting API_MATURITY from a table where it does not exist
: Error: SQLITE_ERROR: no such column: API_MATURITY"}
⇝ (node:2539) UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: no such column: API_MATURITY

bug fix - duplicating endpoints

---

src-electron/db/query-endpoint-type.js
src-electron/generator/helper-session.js
src-electron/generator/template-util.js

- Add more device type information in selectAllEndpointTypes query such as category and package id
- Update user_endpoints query to consider categories such that templates are only generated for their corresponding queries
- Update helpers to use selectAllEndpointTypes instead of exportEndpointTypes to only include endpoints based on the correct category. If category is not specified then generate for everything.
- Fix ensureTemplatePackageId to also check for this.global.genTemplatePackageId

Fix generation issues with respect to template category

---

src-electron/generator/helper-session.js
test/gen-template/zigbee/zap-event.h.zapt
test/multi-protocol.test.js

- After helper waits for the promises to finish. However turning the user_endpoints to async led to accumulator not populate before the iteratorAccumulator tried to access it.
- Turned user-endpoints helper back to no asnyc
- Added test so that this is covered when we actually fix this issue with accumulators
- JIRA: ZAPP-1376

Changing user_endpoints back to non async since that is breaking the backwards compatibility with after and iteratorAccumulator

---

src-electron/db/query-impexp.js
src-electron/importexport/import-json.js

- Throw an error in importEndpointType when device types cannot be found for an endpoint type
- JIRA: ZAPP-1363

Warn users when project linked packages cannot satisfy the .zap file import/open

---

src/components/ZclAttributeManager.vue

when default value is null and the attribute isNullable then the defaultValue is NULL not empty

show NULL when nullable and default is null

---

src-electron/util/types.js

Matter types are lower case not upper case

changing types to lower case for Matter

---

package.json

Add zap-devserver target to make sure instructions on [faq.md](https://github.com/project-chip/zap/blob/master/docs/faq.md?plain=1#L19) could run successfully.

Add zap-devserver target to package.json

---

test/ui.test.js

restructured dom test in test/ui.test.js to avoid local intermittent failures:
dom test relied on a timeout to resolve certain values, changed this to use a promise

restructured dom test in test/ui.test.js to avoid local intermittent failures

---

src-electron/generator/template-util.js
src-electron/importexport/import-json.js
src/store/zap/mutations.js
test/gen-zigbee-7.test.js
test/resource/custom-cluster/custom-device-type.xml
test/test-util.js

Adding standalone packages without considering package category
- Making sure that invalid session Packages are handled properly
- Making sure that sessionPartitionIndex is updated when pacakges are not loaded in the db. Also making sure they are not look into for invalidSessionPkgs since they are already verified for existence
- Adding tests to make sure custom device types are being loaded from custom xml
- JIRA: ZAPP-1450

Show standard clusters when custom device types are added from custom xml

---

src-electron/util/util.js

- Fix possible fails in gen-zigbee-x.test.js unit tests due to inconsistent execution order in async functions
- Replace .then() with await and replace forEach with for loop in ensurePackagesAndPopulateSessionOptions to ensure proper async flow
- Keep using promises in other parts of the function for faster parallel execution

Fix fails in gen-zigbee unit tests

---

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

The naming pattern is a bit different from cluster-specific ones.

Fix Darwin name determination for global structs and enums.

---

src-electron/generator/helper-endpointconfig.js

when a nullable string is null, the javascript code should be a string and not an array so the generated code compiles

fixing issue_1356

---

src-electron/importexport/import-json.js
test/global-setup.js
test/global-teardown.js

- JIRA: ZAPP-1299
- set TEST environment variable before running jest tests, and only print when TEST is false

Remove console prints for compliance when running tests

---

src/components/ZclAttributeManager.vue
src/util/editable-attributes-mixin.js
src/util/ui-options.js

- fix issue #1399
- exclude global attributes from relevantAttributeData to make row number aligns with rendered rows

Fix row number discrepancy in Matter attributes

---

src-electron/db/query-config.js
src-electron/db/query-impexp.js
src-electron/db/query-package.js
src-electron/db/query-zcl.js
src-electron/generator/helper-zcl.js
src-electron/rest/user-data.js
src-electron/sdk/matter.js
src-electron/zcl/zcl-loader-silabs.js
test/matter.test.js

Fixes https://github.com/project-chip/zap/issues/1397
This pull request retrieves the cluster/attribute pairs for all attributeAccessInterface attributes, including those of the list type.
Background: The ATTRIBUTE table designates CLUSTER_REF as null for global attributes.
To incorporate cluster/attribute pairs that are global attributes, the attributeAccessInterface list from zcl.json needs to be imported into an alternative table, PACKAGE_OPTION.
Given that PACKAGE_OPTION exclusively contains pairs enumerated in zcl.json and does not encompass all attributeAccessInterface pairings, it becomes essential to query both the ATTRIBUTE and PACKAGE_OPTION tables.

Issue 1397

---

src-electron/generator/matter/app/zap-templates/templates/app/helper.js

The support for global types was added in commit af33f57. However, it was added only in `zapTypeToPythonClusterObjectType()`. For proper functionality support in `getPythonFieldDefault()` is also required.

Fix support for global types in Python Matter codegen

---

src-electron/db/zap-schema.sql
test/custom-matter-xml.test.js
test/resource/custom-cluster/matter-conflict.xml

- Added triggers to check for mfg code and code conflicts in custom xml. 
- When a session package (that is a manufacturer specific custom xml) is inserted or re-enabled these triggers check for the following:
* If any other custom XMLs linked to the same session have cluster code conflicts
* If any other custom XMLs extend the same cluster and have attribute or command code conflicts
- and adds the relevant session notifications
- Also added triggers to delete all code conflict session notifications related to a session package when that session package is deleted/disabled
- Updated relevant tests to check for these session notifications
ZAPP-1467

added triggers to check for and handle code conflicts in custom XMLs and updated relevant tests

---

src-electron/db/zap-schema.sql
src/pages/NotificationsPage.vue

- Duplicate session notifications
- Number of unseen Notifs don't show up when opening zap
- Number of seen Notifs don't update when drawer is opened
- If a session notice is deleted from the database ZAP UI doesn't reflect it correctly in certain cases
Note: there is an sql formatting issue which created a lot of white space diff

fixed bugs with notification system:

---

src-electron/db/query-impexp.js
src-electron/db/query-session.js
src-electron/importexport/export.js
src-electron/importexport/import-json.js
test/importexport.test.js
test/resource/test-faulty.zap

- During import catch all the duplicate endpoint type attributes, commands and events and continue without inserting these rows.
- Throw session notifications for each of the above issues.
- Upon .zap file save make sure that these warnings go away from the session notification table.
- Add tests for the above.
- Minor cleanup.
- JIRA: ZAPP-1192

Catching duplicate attributes, commands and events in the .zap file and fixing them

---

.github/workflows/unify.yml
src-script/unify-regen.js

Added Unify code generation diff check job:
- Clones the Unify SDK
- Regenerates all the ZAP generated files using working branch of ZAP
- Checks for git diff (fails if there is a diff)

adding Unify code generation diff check

---

.github/workflows/matter.yml
.github/workflows/release.yml
.github/workflows/unify.yml
.github/workflows/zigbee.yml
docs/ZAP-on-Windows.md
docs/development-instructions.md
src-electron/util/env.js

- Update all workflows to use node v20
- Update documentation about using node v20
- JIRA: ZAPP-1494

Update to node v20 for ZAP

---

src/components/ZclEndpointCard.vue

can go back to endpoint config from extensions and options page

---

src/components/ZclCommandManager.vue

- Fixed issue #1424.
- Removed virtual scroll to ensure all commands are properly displayed.
- Added pagination of 50 rows, same as the approach used for attributes.

Fix commands not displayed in Matter clusters

---

src/components/ZclAttributeManager.vue
src/components/ZclCreateModifyEndpoint.vue
src/store/zap/state.js
src/util/ui-options.js

dynamically enabling Matter/Zigbee only components for CMP

---

apack.json

Remove temp state because uc_upgrade now works on Studio without tempstate

---

.github/workflows/release.yml
docs/development-instructions.md
package.json
src-script/build-release-package.js

* added clean script to build release packages
* script can be used in CI and locally
* modified instructions to build binaries locally
* modified release workflow to use build-release-package.js script

ZAPP-1183 added clean script to build release packages

---

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

1) Add device types to availability macro generation. 
2) Add some helpers that allow properly generating device type metadata.

Fix Darwin helpers to allow working with device types.

---

src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js

These were just added, but it turns out they are not actually needed.

Remove unnecessary Darwin helpers.

---

src-electron/ui/window.js

Addressing https://github.com/project-chip/zap/issues/1430

Restore normal titlebar on Linux.

---

package.json
src-electron/db/zap-schema.sql
test/custom-matter-xml.test.js
test/resource/custom-cluster/matter-bad-custom.xml

Added SQL Triggers that check for undefined types in attributes ,command arguments and event fields for a custom XML when inserted into a session. Add session notice as required
Added relevant tests
Corrected typo in package.json

Adding SQL Triggers that check for undefined types in Custom XML

---

apack.json
src-electron/main-process/startup.js
test/resource/upgrade/light.zap
test/startup.test.js

- Create a flag called --upgradeZapFile which can be passed during generation to update the package paths during generation. add this to apack.json
- During generation use the flag to determine if packages should be updated in the .zap file. If the .zap file does not already have the packages mentioned in generation(uc_generate) then the .zap file is updated with those packages and saved.
- JIRA: ZAPP-1456

Update the zcl and template packages during generation

---

src-electron/zcl/zcl-loader-dotdot.js

Unify XMLs have some enums and bitmaps declared as unsigned integers. While they work on cleaning up their XML - added support in ZAP to infer these inconsistencies correctly.

handling enums and bitmaps declared as unsigned integers in Unify XML

---

src-electron/zcl/zcl-loader-silabs.js

- Support parsing attribute name with new format: `<attribute name="attributeName">`
- Will not affect current parsing format including `<attribute>attributeName</attribute>` and `<description> attributeName</description>`
- Required by [#36223](https://github.com/project-chip/connectedhomeip/pull/36233) as CHIP XMLs are moving to the new format

Support Parsing "name" inside Attribute Tag

---

apack.json
docs/api.md
docs/helpers.md
src-electron/generator/helper-attribute.js
test/gen-template/zigbee/zap-config-version-3.zapt
test/multi-protocol.test.js
zcl-builtin/silabs/multi-protocol.json

- as_underlying_atomic_identifier_for_attributeId checks for the attribute type and returns the atomic identifier associated with it.
- JIRA: ZAPP-1385

Add helper to determine the atomic identifier for attribute Id given

---

src-electron/zcl/zcl-loader-silabs.js

- Added support to process domain data from XML in both formats: `<domain>General</domain>` (current) and `<domain name="General"/>` (new)
- Make ZAP compatible with parsing CHIP XMLs updated by Alchemy

Update logic to process domain data

---

README.md
docs/external-helpers.md

Adding readMe for instructions on how to create External Helpers

doc for external helpers

---

docs/api.md
src-electron/validation/validation.js
test/validation.test.js

- Also got rid of `isValidSignedNumberString()` since it was redundant code.
ZAPP-1536

Attribute validation defaults to minimum and maximum defined by type if not defined by attribute.

---

src/components/ZclCreateModifyEndpoint.vue
src/store/zap/actions.js

- call API directly without action
- check if $serverGet is defined before calling it
- the change would help #1482 pass unit tests and prevent `ui.test.js` from failing in the future

Restructure getEndpointIds function to pass ui.test.js

---

docs/api.md
src-electron/db/query-loader.js
src-electron/zcl/zcl-loader-silabs.js
zcl-builtin/matter/data-model/chip/matter-devices.xml

Pull Request Summary
Title: Enable Multiple Endpoints and Device Types in Device Composition Insertion
Description:
This update enhances the insertDeviceComposition function to support multiple endpoints and multiple device types (deviceType) per endpoint. Previously, the code could only insert data for a single endpoint and device type.
Key Changes:
Multiple Endpoints: The function now processes all endpoints in deviceType.composition.endpoint, inserting data for each.
Multiple Device Types per Endpoint: Supports inserting multiple deviceType values per endpoint.
Dynamic Conformance and Constraint: Uses endpoint-specific conformance and constraint values when available, with fallbacks to default deviceType values.
Improved Error Handling: Ensures required data is present and correctly …

Enable Multiple Endpoints and Device Types in Device Composition Insertion

---

.github/workflows/release.yml
src-script/install-packages-osx

also using 7zip pre-installed library instead of using node module

updating to macos-14

---

src-electron/db/query-attribute.js
src-electron/db/query-command.js
src-electron/db/query-event.js
src-electron/rest/user-data.js
test/query.test.js

- Updated endpoint type attribute query to join DEVICE_TYPE_CLUSTER table, ensuring disabled attributes are retrieved when opening a ZAP file.
- Fixed bug where element conformance warnings were not displayed after opening a ZAP file.
- Adapted unit tests to changes in the functions.

Feature Page Improvement: Display attribute conformance warning when open ZAP file

---

src/App.vue
src/store/zap/actions.js

This pull request introduces functionality to track and manage the "dirty" state of ZAP configuration by listening for WebSocket events indicating unsaved changes. Specifically, the code listens for the dirtyFlag WebSocket event, and upon receiving this event, it triggers an action to update the application's dirty state.
**Changes:**
**WebSocket listener:** Added a WebSocket listener for the dirtyFlag event, which dispatches the setDirtyState action to update the application state when unsaved changes are detected.
**Action:** The setDirtyState action is responsible for fetching the current dirty state from the backend using the isDirty API endpoint and committing the result to the store.
**Mutation:** The setDirtyState mutation updates the state with the new dirty flag (isDirty) and …

Studio V6 Add WebSocket listener to track unsaved changes and update dirty state for ZAP configuration

---

docs/api.md
src/App.vue
src/api/renderer_api.js
src/store/zap/actions.js
src/store/zap/mutations.js

0. Remove the whole process of registering a second socket listener to the same event.
1. Retain only one dirtyFlag notifier.
2. Add the transformation from the default ZAP data format, towards the IDE data format.
3. Remove state transitions in VueX store. These are not needed at all.

Clean up the duplicate dirty flag mechanism.

---

src-electron/db/db-mapping.js
src-electron/db/query-zcl.js
src-electron/generator/helper-zcl.js
test/gen-matter-3-1.test.js
test/gen-template/matter3/miscellaneous_helper_tests.zapt
test/test-util.js
zcl-builtin/matter/data-model/chip/test-cluster.xml

Fix for https://github.com/project-chip/zap/issues/1500

Take into consideration transitive dependencies, not just root struct fields

---

src-electron/ui/browser-api.js
src-electron/ui/menu.js
src/boot/axios.js
src/boot/ws.js
src/util/session-id.js

This should resolve issues related to session handling.
There are two modes of operation:
1.) WITHOUT a passed appId, in which case we simply use a default value, and map the uuid to that key.
2.) WITH a passed appId (which is called "stsApplicationId" on the query string). In this case, this appId is being used to key the uuid inside the session map.
The second case is used when zap is rendered inside a system with multiple iframes, which share the same "sessionStorage", so you have to kepe session separate. That's why you can't simly use session storage directly.
The map ensures two things:
1.) When an iframe refreshes, with the same appId, it will reattach to the same sessionId.
2.) When a whole new iframe is created, and a new appId is passed, the whole new uuid will get created.

Deal with session handling.

---

docs/api.md
src/components/ZclDomainClusterView.vue

GitHub Issue: #1506 
JIRA: GHM_ZAP-474
- hide warning icon for disabled required clusters only when ZAP is not in standalone mode
- clean up unused code
- correct documentation changes in `docs/api.md` from #1497

Fix warning not displayed when required cluster is diabled

---

docs/api.md
src-electron/db/query-feature.js
src-electron/importexport/import-json.js
src-electron/rest/user-data.js

JIRA: ZAPP-1565
- Add element conformance warnings to the notification system when opening a ZAP file.
- Print warnings to the console
- Relocate several functions to improve code structure, will do a clean up PR later for further improvement

Set element conformance notifications on file opening

---

src-electron/db/query-session.js
src-electron/rest/user-data.js
src-electron/zcl/zcl-loader-silabs.js
test/custom-matter-xml.test.js

- Ensure that when a package is added to a session where a session package with the given package ID already exists, the existing session package is re-enabled instead of creating a new session package.
- Removed redundant code in httpPostAddNewPackage()
- Added tests
ZAPP-1582

Fix: Re-enable existing session package instead of adding duplicate

---

package-lock.json

Unit tests were failing when running locally due to the outdated `caniuse-lite` package. Running ZAP and unit tests displayed the following warning:
```
⇝ Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
```
This PR updates `caniuse-lite` by executing the command above, removing the warning and helping the test failures.

Update caniuse-lite package

---

package.json

Pushing a tag was creating a release and a duplicate draft release with the same tag name. This draft release was unintended and was being caused by electron-builders publish behavior. Fixing this by disabling "publish" in electron-builder config.

Fixing unintentional draft release creation upon tag push

---

docs/api.md
src-electron/zcl/zcl-loader-silabs.js
src-electron/zcl/zcl-loader.js
test/custom-matter-xml.test.js
test/gen-matter-1.test.js
test/gen-template/matter/simple-test.zapt
test/resource/custom-cluster/custom-xml-in-zcl-json.xml
test/test-util.js
zcl-builtin/matter/data-model/chip/thermostat-cluster.xml
zcl-builtin/matter/zcl.json

- Updated processClusterExtensions which is part of the delayed promises to load custom data types within clusterExtensions tag.
- Now users can define custom data types within clusterExtensions referring to other data types within standard xml.
- Added Unit tests for the same
- Github: ZAP#1529

Adding clusterExtension Support from standard xml file loading like we do from zcl.json

---

src-electron/zcl/zcl-loader-silabs.js
test/gen-matter-1.test.js
zcl-builtin/matter/data-model/chip/low-power-cluster.xml

- Loading the data type and bitmap tables by cluster codes in features
- Adding tests to check that Feature bitmap and bitmap field entries are loaded per cluster mentioned
- Github: ZAP#1306

Allow Features to have cluster codes just like bitmaps and other data types

---

src-electron/zcl/zcl-loader-silabs.js
test/zcl-loader.test.js
zcl-builtin/matter/data-model/chip/access-control-cluster.xml

- This PR adapts ZAP to support parsing list type definition `array="true" type="X"` for attributes, ensuring consistency with command and event definitions in the XML.
- ZAP now converts `array="true" type="X"` to `type="array" entryType="X"` before parsing, allowing support for both formats.
- This update prepares ZAP for upcoming XML changes to standardize list type definitions across elements
- Issue: #1474
- Jira: GHM_ZAP-461

Adapt ZAP to Support Both List Type Definition Formats for Attributes

---

src-electron/db/query-loader.js
src-electron/generator/matter/controller/python/templates/helper.js
src-electron/zcl/zcl-loader-silabs.js
test/zcl-loader.test.js
zcl-builtin/matter/data-model/chip/binding-cluster.xml
zcl-builtin/matter/data-model/chip/descriptor-cluster.xml

- This solves the issue of loading a same named generic and cluster specific data type.
- The issue was with the generic data type type searches not checking if their cluster reference does not exist and thus getting the cluster specific data type instead. Now that check is added and duplicates issue is resolved
- Ran into another ZAP generation issue while running zap_regen_all.py and fixed that error in helper.js
- Github: ZAP#1540

Allow cluster specific and generic data types with the same name in the XML

---

src-electron/importexport/export.js
src-electron/importexport/import-json.js

Relative paths don't exist across two different drives. On file import if package is in different drive than home dir or zap file location, package relativity will be changed to absolute for that package.
ZAPP-1087

Fix: Handling package paths in different drives than user home dir or zap file location

---

cypress/e2e/endpoints/edit-endpoint.cy.js
src/components/ZclCreateModifyEndpoint.vue
src/components/ZclEndpointCard.vue

- Currently when a user edits the device type on an endpoint configuration then the configuration is overwritten on top of the existing endpoint configuration.
- However the above can lead to non-compliant device type as per the protocol specification if the users are not careful.
- With this change a dialogue pops up when the user changes the device type to either edit on top of existing endpoint config or add as a new endpoint config.
- Added cypress tests to cover the same
- Github: ZAP#1125

Allow user to edit a device type on an existing endpoint as a new endpoint config and not an overwrite on existing endpoint config

---

docs/sdk-integration.md
src-electron/db/db-mapping.js
src-electron/db/query-struct.js
src-electron/db/query-zcl.js
src-electron/generator/helper-zcl.js
test/gen-matter-3-1.test.js
test/gen-template/matter3/miscellaneous_helper_tests.zapt

- Fixed the zcl_struct_items_by_struct_and_cluster_name helper for this global vs cluster specific struct items
- Added tests for it
- Github: ZAP#1551

Handling struct items properly when we have a global and cluster specific struct with the same name

---

docs/api.md
src-electron/db/db-mapping.js
src-electron/db/query-feature.js
src-electron/rest/static-zcl.js
src-electron/rest/user-data.js
src-shared/db-enum.js
src-shared/rest-api.js
src/components/ZclClusterFeatureManager.vue
src/components/ZclClusterView.vue
src/components/ZclDeviceTypeFeatureManager.vue
src/components/ZclDomainClusterView.vue
src/css/app.sass
src/store/zap/actions.js
src/store/zap/mutations.js
src/store/zap/state.js
src/util/common-mixin.js
test/feature.test.js
test/test-query.js
test/test-util.js

- Implemented the Cluster Feature page to display feature details and enabled status based on cluster XML definitions.
(Note: Feature toggling is currently disabled and will be enabled in a future PR.)
- Displayed the FeatureMap Attribute Value on the top right corner of the page to assist with feature configuration.
- Added backend logic and REST APIs
- Added unit test for API getting featureMap attribute value
ZAPP-1547

Cluster Feature Page - Display Feature Info

---

docs/sdk-integration.md
src-electron/util/util.js
test/util.test.js

Supports the `touppercamelcase` in addition to `tocamelcase` in the iterator for creating split templates.
This is to prepare for project-chip/connectedhomeip#38207

Support touppercamelcase in iterator for split templates

---

docs/api.md
src-electron/db/query-struct.js
src-electron/db/query-util.js
src-electron/db/query-zcl.js
src-electron/generator/matter/darwin/Framework/CHIP/templates/helper.js
test/gen-matter-3-1.test.js

- Add selectStructByNameAndClusterName because selectStructByNameAndClusterId could not be used for some of our existing helpers such as asObjectiveCClass.
- Update query-util.js to form the correct data type retrieval using data type name and cluster name: sqlQueryForDataTypeByNameAndClusterName
- Update asObjectiveCClass with selectStructByNameAndClusterName instead of selectStructByName
- Github: ZAP#1559

Clean up helper when structs with same name exist as a global struct and a cluster specific one

---

.github/workflows/matter.yml
src-electron/generator/helper-c.js
test/helpers.test.js

- See the unit test to understand the issue here where 1600 should not be 0x640 but 0x0640 for proper endian conversion
- Added unit tests
- JIRA: ZAPP-1610

Fix endianness issue when the hex value length is odd

---

docs/api.md
src-electron/generator/generation-engine.js

When json files referenced from within the templates.json file are updated then checksum is calculated for those as well and updated accordingly.

Bug/update gen templates json file for nested files/zapp 1297

---

docs/api.md
src-electron/db/query-bitmap.js
src-electron/db/query-enum.js
src-electron/db/query-struct.js
src-electron/db/query-zcl.js
test/gen-matter-3-1.test.js
zcl-builtin/matter/data-model/chip/descriptor-cluster.xml
zcl-builtin/matter/data-model/chip/mode-select-cluster.xml

Adding search by enum/bitmap name and Cluster name

---

src-electron/generator/matter/app/zap-templates/common/ClusterTestGeneration.js
src-electron/generator/matter/app/zap-templates/templates/app/helper.js

NOTE: the Matter generation changes here are somewhat expected, because some of the new template changes in Matter are buggy until https://github.com/project-chip/connectedhomeip/pull/38733 merges.  There should be no compat impact here for Matter bits from older Matter releases.

Fix Matter helpers to do the right thing with global enums/bitmaps.

---

docs/api.md
src-electron/util/env.js
src-electron/validation/conformance-expression-evaluator.js
src-electron/validation/conformance-xml-parser.js
src-electron/zcl/zcl-loader-silabs.js
src-shared/db-enum.js
test/test-query.js
test/zcl-loader.test.js
zcl-builtin/matter/data-model/chip/door-lock-cluster.xml

ZAP XMLs currently declare optionality redundantly—via optional attribute and conformance tag.
This PR makes ZAP interpret either source and ready for removing optional attribute in the future.
Issue: #1526 
GHM_ZAP-477
- Extend optionality logic for attributes, commands, and events: an element is now treated as optional when either `optional="true"` or its conformance ≠ `'M'` (mandatory).
- Add unit tests covering all combinations of optional attribute and conformance definitions
- Update ZAP XMLs for testing purpose. The conformance data are obtained from CHIP ZAP XMLs
Let optional attribute takes precedence over conformance for backwards compatibility like the element below:
```
<attribute side="server" code="0x02" name="UpTime" define="UP_TIME" type="int64u" optional="true"> …
```

Resolve element optionality via both optional attribute and conformance

---

src-electron/util/types.js
test/gen-matter-3-1.test.js
test/resource/multiple-device-types-per-endpoint.zap

Generating correctly for string type attributes which have numbers only as their default values when using helper-endpointconfig.js
Github: ZAP#1504

Fixing endpoint config generation for string type attributes

---

docs/api.md
src-electron/db/query-config.js
src-electron/rest/user-data.js
src-electron/validation/conformance-checker.js
src-electron/validation/conformance-expression-evaluator.js
src-electron/validation/conformance-xml-parser.js
src-shared/db-enum.js
src/components/ZclDeviceTypeFeatureManager.vue
src/components/ZclEventManager.vue

- Added a confirmation dialog when user toggles a device type feature. After viewing the list of elements to be updated, user can choose to proceed with the change or cancel it.
- Disabled toggling of a device type feature if its associated cluster is disabled, and displayed warnings to inform user which cluster is missing.
ZAPP-1549, ZAPP-1552

Add Confirmation Dialog on Device Type Feature Toggle and Disable Toggling when Related Cluster is Disabled

---

docs/api.md
src-electron/db/db-api.js
src-electron/util/async-reporting.js

- Believe that this was being caused by asynchronous reporting that we do for dirty flag and session notification counts on a periodic interval. When we close ZAP some of these reporting events are running queries on a closed database and thus throw a bunch of errors. The changes here stop the asynchronous reporting events from running when the database has been closed.
- JIRA: ZAPP-1607

When closing ZAP sometimes a system error shows up

---

src-electron/generator/helper-endpointconfig.js
test/custom-matter-xml.test.js
test/gen-matter-3-1.test.js
test/resource/custom-cluster/matter-conflict.xml
test/resource/custom-cluster/matter-custom.xml
zcl-builtin/dotdot/BallastConfiguration.xml

- Fixing the generation of min and max values to be auto assumed and generated correctly when either min or max are mentioned instead of both min and max
- Also making sure we do not always typecase everything to (uint16_t) but instead typecast the values based on size and sign
- Github: ZAP #1615

Fixing the generation for Attribute Min Max used in endpoint_config.h
